Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: Malamute
        repo: https://hpcgitlab.hpc.inl.gov/idaholab/malamute
        menu:
          Documentation:
            Complete Code Manual: syntax/index.md
            Software Quality Assurance (SQA): sqa/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms:
            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            malamute: !include ${ROOT_DIR}/doc/sqa_malamute.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://hpcgitlab.hpc.inl.gov/idaholab/malamute
    MooseDocs.extensions.template:
        active: true
