Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content
    - ${MOOSE_DIR}/modules/heat_conduction/doc/content
    - ${MOOSE_DIR}/modules/ray_tracing/doc/content  # pulled in by heat_conduction
    - ${MOOSE_DIR}/modules/level_set/doc/content
    - ${MOOSE_DIR}/modules/navier_stokes/doc/content
    - ${MOOSE_DIR}/modules/fluid_properties/doc/content # pulled in by navier_stokes
    - ${MOOSE_DIR}/modules/rdg/doc/content  # pulled in by navier_stokes
    - ${MOOSE_DIR}/modules/phase_field/doc/content
    - ${MOOSE_DIR}/modules/tensor_mechanics/doc/content
    - ${MOOSE_DIR}/modules/level_set/doc/content
    - infrastructure:  # needed due to tensor_mechanics SQA
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - help/finite_element_concepts/nodal_patch_recovery.md
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: Malamute
        repo: https://hpcgitlab.hpc.inl.gov/idaholab/malamute
        menu:
          Getting Started:
            Installation: getting_started/installation.md
            Using MALAMUTE: getting_started/using_malamute.md
          Documentation and Resources:
            Complete Code Manual: syntax/index.md
            Code Standards: development/code_standards.md
            Developer Information Links: development/moose_developer_info.md
            Software Quality Assurance (SQA) Information: /sqa/index.md
            Code Coverage: https://malamute-dev.hpc.inl.gov/coverage/
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms:
            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            malamute: !include ${ROOT_DIR}/doc/sqa_malamute.yml
            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/sqa_heat_conduction.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            navier_stokes: !include ${MOOSE_DIR}/modules/navier_stokes/doc/sqa_navier_stokes.yml
            fluid_properties: !include ${MOOSE_DIR}/modules/fluid_properties/doc/sqa_fluid_properties.yml
            rdg: !include ${MOOSE_DIR}/modules/rdg/doc/sqa_rdg.yml
            phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/sqa_phase_field.yml
            tensor_mechanics: !include ${MOOSE_DIR}/modules/tensor_mechanics/doc/sqa_tensor_mechanics.yml
            level_set: !include ${MOOSE_DIR}/modules/level_set/doc/sqa_level_set.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://hpcgitlab.hpc.inl.gov/idaholab/malamute
    MooseDocs.extensions.template:
        active: true
    MooseDocs.extensions.bibtex:
        duplicates:
          - greenshields2010implementation
          - batten1997average
          - hales15homogenization
          - kim_phase-field_1999
